#!/usr/bin/env sh

# ~/.config/bspwm/bspwmrc
# bspwm configuration file

bspc rule -r "*"

# multiple monitors support
if [ "$(xrandr -q | grep " connected" | awk '{print $1}' | wc -l)" -eq "2" ]; then
	~/.screenlayout/dock.sh
	bspc monitor eDP-1-1 -d I II III IV V
	bspc monitor HDMI-0 -d VI VII VIII IX X
else
	xrandr -s 0
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

# general
bspc config border_width 3
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

# colors
bspc config normal_border_color "#383838"
bspc config active_border_color "#383838"
bspc config focused_border_color "#86c1b9"
bspc config presel_feedback_color "#86c1b9"

# window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
dunst &
playerctld daemon &

xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &
xset s 300 5 &

nm-applet &
blueman-applet &
optimus-manager-qt &

~/.fehbg &

# Terminate already running bar instances
killall -q redshift

# Wait until the processes have been shut down
while pgrep -x redshift >/dev/null; do sleep 1; done
redshift &
